name: aws deployment

on: push


jobs:
    deployAws:
        runs-on: ubuntu-latest
        permissions:
            id-token: write # This is required for requesting the JWT
            contents: read  # This is required for actions/checkout

        steps:
            - name: cloning repo
              uses: actions/checkout@v3


            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
               aws-region: us-east-1
               role-to-assume: arn:aws:iam::176377892878:role/aws_link1
               role-session-name: awsconf1

            - name: testing aws configure
              run: aws s3 ls
